main: com.legit.globalrep.RepDriver
name: GlobalRep
version: 1.8
author: aasmus
description: Cross Server Reputation Plugin
commands:
  rep:
    description: plugin usage command
    usage: /rep
    permission: rep.allow
    permission-message: You don't have the rep.allow permission node.
permissions:
  rep.allow:
    description: grants access to /rep commands
    default: true
  rep.delete.self:
    description: allows you to delete reputation records that you have made
    default: false
  rep.delete.others:
    description: allows user to delete others reputation records
    default: op
  rep.delete:
    description: allows user to delete others reputation records
    default: false
  rep.amount.1:
    description: gives the player a rep power of 1
    default: true
  rep.amount.2:
    description: gives the player a rep power of 2
    default: false
  rep.amount.3:
    description: gives the player a rep power of 3
    default: false
  rep.amount.4:
    description: gives the player a rep power of 4
    default: false
  rep.amount.5:
    description: gives the player a rep power of 5
    default: false
  rep.amount.6:
    description: gives the player a rep power of 6
    default: false
  rep.amount.7:
    description: gives the player a rep power of 7
    default: false
  rep.amount.8:
    description: gives the player a rep power of 8
    default: false
  rep.amount.9:
    description: gives the player a rep power of 9
    default: false
  rep.amount.10:
    description: gives the player a rep power of 10
    default: op
